name: PyInstaller

on: [push]

jobs:
  buildMac1:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests esptool zeroconf PyQt5
    - name: build with pyinstaller
      run: |
        pyinstaller airrohr-flasher.spec
        ls
        ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher
        path: dist/airrohr-flasher
  buildUbuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt install qttools5-dev-tools pyqt5-dev-tools qt5-default python3-pip python3.6 make
    - name: build with pyinstaller
      run: |
        make deps dist && ls dist/
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher-ubuntu
        path: dist/airrohr-flasher
      
  buildMac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6 
      - name: Build App
        run: |
          export PATH="$HOME/Qt/5.11.1/clang_64/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"
          make deps dmg
          ls dist
      - uses: actions/upload-artifact@v2
        with:
          name: airrohr-flasher-mac
          path: dist/airrohr-flasher
    
  buildWin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6 
      - name: Build App
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests esptool zeroconf PyQt5
          pyinstaller airrohr-flasher.spec
      - uses: actions/upload-artifact@v2
        with:
          name: airrohr-flasher-win
          path: dist/airrohr-flasher.exe
          
