name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt install qttools5-dev-tools pyqt5-dev-tools qt5-default python3-pip python3.6 make
    - name: build with pyinstaller
      run: |
        make deps dist && ls dist/
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher
        path: dist/airrohr-flasher
