name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller airrohr-flasher.spec
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher
        path: dist/airrohr-flasher
